# Generated by Django 2.2.5 on 2020-10-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20201017_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='date',
            new_name='reserve_date',
        ),
    ]
